<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Stripe Merchant Category Codes (MCC)
 *
 * @see https://docs.stripe.com/connect/setting-mcc#list
 */
enum StripeMerchantCategoryCode: string
{
    case AcRefrigerationRepair = '7623';
    case AccountingBookkeepingServices = '8931';
    case AdvertisingServices = '7311';
    case AgriculturalCooperative = '0763';
    case AirlinesAirCarriers = '4511';
    case AirportsflyingFields = '4582';
    case AmbulanceServices = '4119';
    case AntiqueReproductions = '5937';
    case AntiqueShops = '5932';
    case Aquariums = '7998';
    case ArchitecturalSurveyingServices = '8911';
    case ArtDealersAndGalleries = '5971';
    case ArtistsSupplyAndCraftShops = '5970';
    case AutoBodyRepairShops = '7531';
    case AutoPaintShops = '7535';
    case AutoServiceShops = '7538';
    case AutoAndHomeSupplyStores = '5531';
    case AutomatedFuelDispensers = '5542';
    case AutomobileAssociations = '8675';
    case AutomotivePartsAndAccessoriesStores = '5533';
    case AutomotiveTireStores = '5532';
    case BailAndBondPayments = '9223';
    case Bakeries = '5462';
    case BandsOrchestras = '7929';
    case BarberAndBeautyShops = '7230';
    case BettingCasinoGambling = '7995';
    case BicycleShops = '5940';
    case BilliardPoolEstablishments = '7932';
    case BoatDealers = '5551';
    case BoatRentalsAndLeases = '4457';
    case BookStores = '5942';
    case BooksPeriodicalsAndNewspapers = '5192';
    case BowlingAlleys = '7933';
    case BusLines = '4131';
    case BusinessSecretarialSchools = '8244';
    case BuyingShoppingServices = '7278';
    case CableSatelliteAndOtherPayTelevisionAndRadio = '4899';
    case CameraAndPhotographicSupplyStores = '5946';
    case CandyNutAndConfectioneryStores = '5441';
    case CarRentalAgencies = '7512';
    case CarWashes = '7542';
    case CarAndTruckDealersNewUsed = '5511';
    case CarAndTruckDealersUsedOnly = '5521';
    case CarpentryServices = '1750';
    case CarpetUpholsteryCleaning = '7217';
    case Caterers = '5811';
    case CharitableAndSocialServiceOrganizationsFundraising = '8398';
    case ChemicalsAndAlliedProducts = '5169';
    case ChildCareServices = '8351';
    case ChildrensAndInfantsWearStores = '5641';
    case ChiropodistsPodiatrists = '8049';
    case Chiropractors = '8041';
    case CigarStoresAndStands = '5993';
    case CivicSocialFraternalAssociations = '8641';
    case CleaningAndMaintenance = '7349';
    case ClothingRental = '7296';
    case CollegesUniversities = '8220';
    case CommercialEquipment = '5046';
    case CommercialFootwear = '5139';
    case CommercialPhotographyArtAndGraphics = '7333';
    case CommuterTransportAndFerries = '4111';
    case ComputerNetworkServices = '4816';
    case ComputerProgramming = '7372';
    case ComputerRepair = '7379';
    case ComputerSoftwareStores = '5734';
    case ComputersPeripheralsAndSoftware = '5045';
    case ConcreteWorkServices = '1771';
    case ConstructionMaterials = '5039';
    case ConsultingPublicRelations = '7392';
    case CorrespondenceSchools = '8241';
    case CosmeticStores = '5977';
    case CounselingServices = '7277';
    case CountryClubs = '7997';
    case CourierServices = '4215';
    case CourtCosts = '9211';
    case CreditReportingAgencies = '7321';
    case CruiseLines = '4411';
    case DairyProductsStores = '5451';
    case DanceHallStudiosSchools = '7911';
    case DentistsOrthodontists = '8021';
    case DepartmentStores = '5311';
    case DetectiveAgencies = '7393';
    case DigitalGoodsMediaBooksMoviesMusic = '5815';
    case DigitalGoodsApplications = '5817';
    case DigitalGoodsGames = '5816';
    case DigitalGoodsLargeVolume = '5818';
    case DirectMarketingCatalogMerchant = '5964';
    case DirectMarketingCombinationCatalogAndRetailMerchant = '5965';
    case DirectMarketingInboundTelemarketing = '5967';
    case DirectMarketingInsuranceServices = '5960';
    case DirectMarketingOther = '5969';
    case DirectMarketingOutboundTelemarketing = '5966';
    case DirectMarketingSubscription = '5968';
    case DirectMarketingTravel = '5962';
    case DiscountStores = '5310';
    case Doctors = '8011';
    case DoorToDoorSales = '5963';
    case DraperyWindowCoveringAndUpholsteryStores = '5714';
    case DrinkingPlaces = '5813';
    case DrugStoresAndPharmacies = '5912';
    case DrugsDrugProprietariesAndDruggistSundries = '5122';
    case DryCleaners = '7216';
    case DurableGoods = '5099';
    case DutyFreeStores = '5309';
    case EatingPlacesRestaurants = '5812';
    case EducationalServices = '8299';
    case ElectricRazorStores = '5997';
    case ElectricVehicleCharging = '5552';
    case ElectricalPartsAndEquipment = '5065';
    case ElectricalServices = '1731';
    case ElectronicsRepairShops = '7622';
    case ElectronicsStores = '5732';
    case ElementarySecondarySchools = '8211';
    case EmergencyServicesGcasVisaUseOnly = '9702';
    case EmploymentTempAgencies = '7361';
    case EquipmentRental = '7394';
    case ExterminatingServices = '7342';
    case FamilyClothingStores = '5651';
    case FastFoodRestaurants = '5814';
    case FinancialInstitutions = '6012';
    case FinesGovernmentAdministrativeEntities = '9222';
    case FireplaceFireplaceScreensAndAccessoriesStores = '5718';
    case FloorCoveringStores = '5713';
    case Florists = '5992';
    case FloristsSuppliesNurseryStockAndFlowers = '5193';
    case FreezerAndLockerMeatProvisions = '5422';
    case FuelDealersNonAutomotive = '5983';
    case FuneralServicesCrematories = '7261';
    case FurnitureRepairRefinishing = '7641';
    case FurnitureHomeFurnishingsAndEquipmentStoresExceptAppliances = '5712';
    case FurriersAndFurShops = '5681';
    case GeneralServices = '1520';
    case GiftCardNoveltyAndSouvenirShops = '5947';
    case GlassPaintAndWallpaperStores = '5231';
    case GlasswareCrystalStores = '5950';
    case GolfCoursesPublic = '7992';
    case GovernmentLicensedOnlineCasionsOnlineGamblingUsRegionOnly = '7801';
    case GovernmentServices = '9399';
    case GovernmentLicensedHorseDogRacingUsRegionOnly = '7802';
    case GovernmentOwnedLotteriesNonUsRegion = '9406';
    case GovernmentOwnedLotteriesUsRegionOnly = '7800';
    case GroceryStoresSupermarkets = '5411';
    case HardwareStores = '5251';
    case HardwareEquipmentAndSupplies = '5072';
    case HealthAndBeautySpas = '7298';
    case HearingAidsSalesAndSupplies = '5975';
    case HeatingPlumbingAc = '1711';
    case HobbyToyAndGameShops = '5945';
    case HomeSupplyWarehouseStores = '5200';
    case Hospitals = '8062';
    case HotelsMotelsAndResorts = '7011';
    case HouseholdApplianceStores = '5722';
    case IndustrialSupplies = '5085';
    case InformationRetrievalServices = '7375';
    case InsuranceUnderwritingPremiums = '6300';
    case IntraCompanyPurchases = '9950';
    case JewelryStoresWatchesClocksAndSilverwareStores = '5944';
    case LandscapingServices = '0780';
    case Laundries = '7211';
    case LaundryCleaningServices = '7210';
    case LegalServicesAttorneys = '8111';
    case LuggageAndLeatherGoodsStores = '5948';
    case LumberBuildingMaterialsStores = '5211';
    case MarinasServiceAndSupplies = '4468';
    case MasonryStoneworkAndPlaster = '1740';
    case MassageParlors = '7297';
    case MedicalServices = '8099';
    case MedicalAndDentalLabs = '8071';
    case MedicalDentalOphthalmicAndHospitalEquipmentAndSupplies = '5047';
    case MembershipOrganizations = '8699';
    case MensAndBoysClothingAndAccessoriesStores = '5611';
    case MensWomensClothingStores = '5691';
    case MetalServiceCenters = '5051';
    case MiscellaneousApparelAndAccessoryShops = '5699';
    case MiscellaneousAutoDealers = '5599';
    case MiscellaneousBusinessServices = '7399';
    case MiscellaneousFoodStores = '5499';
    case MiscellaneousGeneralMerchandise = '5399';
    case MiscellaneousGeneralServices = '7299';
    case MiscellaneousHomeFurnishingSpecialtyStores = '5719';
    case MiscellaneousPublishingAndPrinting = '2741';
    case MiscellaneousRecreationServices = '7999';
    case MiscellaneousRepairShops = '7699';
    case MiscellaneousSpecialtyRetail = '5999';
    case MobileHomeDealers = '5271';
    case MotionPictureTheaters = '7832';
    case MotorFreightCarriersAndTrucking = '4214';
    case MotorHomesDealers = '5592';
    case MotorVehicleSuppliesAndNewParts = '5013';
    case MotorcycleShopsAndDealers = '5571';
    case MotorcycleShopsDealers = '5561';
    case MusicStoresMusicalInstrumentsPianosAndSheetMusic = '5733';
    case NewsDealersAndNewsstands = '5994';
    case NonFiMoneyOrders = '6051';
    case NonFiStoredValueCardPurchaseLoad = '6540';
    case NondurableGoods = '5199';
    case NurseriesLawnAndGardenSupplyStores = '5261';
    case NursingPersonalCare = '8050';
    case OfficeAndCommercialFurniture = '5021';
    case OpticiansEyeglasses = '8043';
    case OptometristsOphthalmologist = '8042';
    case OrthopedicGoodsProstheticDevices = '5976';
    case Osteopaths = '8031';
    case PackageStoresBeerWineAndLiquor = '5921';
    case PaintsVarnishesAndSupplies = '5198';
    case ParkingLotsGarages = '7523';
    case PassengerRailways = '4112';
    case PawnShops = '5933';
    case PetShopsPetFoodAndSupplies = '5995';
    case PetroleumAndPetroleumProducts = '5172';
    case PhotoDeveloping = '7395';
    case PhotographicStudios = '7221';
    case PhotographicPhotocopyMicrofilmEquipmentAndSupplies = '5044';
    case PictureVideoProduction = '7829';
    case PieceGoodsNotionsAndOtherDryGoods = '5131';
    case PlumbingHeatingEquipmentAndSupplies = '5074';
    case PoliticalOrganizations = '8651';
    case PostalServicesGovernmentOnly = '9402';
    case PreciousStoneAndMetalsWatchesAndJewelry = '5094';
    case ProfessionalServices = '8999';
    case PublicWarehousingAndStorage = '4225';
    case QuickCopyReproAndBlueprint = '7338';
    case Railroads = '4011';
    case RealEstateAgentsAndManagersRentals = '6513';
    case RecordStores = '5735';
    case RecreationalVehicleRentals = '7519';
    case ReligiousGoodsStores = '5973';
    case ReligiousOrganizations = '8661';
    case RoofingSidingSheetMetal = '1761';
    case SecretarialSupportServices = '7339';
    case SecurityBrokersDealers = '6211';
    case ServiceStations = '5541';
    case SewingNeedleworkFabricAndPieceGoodsStores = '5949';
    case ShoeRepairHatCleaning = '7251';
    case ShoeStores = '5661';
    case SmallApplianceRepair = '7629';
    case SnowmobileDealers = '5598';
    case SpecialTradeServices = '1799';
    case SpecialtyCleaning = '2842';
    case SportingGoodsStores = '5941';
    case SportingRecreationCamps = '7032';
    case SportsClubsFields = '7941';
    case SportsAndRidingApparelStores = '5655';
    case StampAndCoinStores = '5972';
    case StationeryStoresOfficeAndSchoolSupplyStores = '5943';
    case StationeryOfficeSuppliesPrintingAndWritingPaper = '5111';
    case SwimmingPoolsSales = '5996';
    case TuiTravelGermany = '4723';
    case TailorsAlterations = '5697';
    case TaxPaymentsGovernmentAgencies = '9311';
    case TaxPreparationServices = '7276';
    case TaxicabsLimousines = '4121';
    case TelecommunicationEquipmentAndTelephoneSales = '4812';
    case TelecommunicationServices = '4814';
    case TelegraphServices = '4821';
    case TentAndAwningShops = '5998';
    case TestingLaboratories = '8734';
    case TheatricalTicketAgencies = '7922';
    case Timeshares = '7012';
    case TireRetreadingAndRepair = '7534';
    case TollsBridgeFees = '4784';
    case TouristAttractionsAndExhibits = '7991';
    case TowingServices = '7549';
    case TrailerParksampgrounds = '7033';
    case TransportationServices = '4789';
    case TravelAgenciesTourOperators = '4722';
    case TruckUtilityTrailerRentals = '7513';
    case TypesettingPlateMakingAndRelatedServices = '2791';
    case TypewriterStores = '5978';
    case UsFederalGovernmentAgenciesOrDepartments = '9405';
    case UniformsCommercialClothing = '5137';
    case UsedMerchandiseAndSecondhandStores = '5931';
    case Utilities = '4900';
    case VarietyStores = '5331';
    case VeterinaryServices = '0742';
    case VideoAmusementGameSupplies = '7993';
    case VideoGameArcades = '7994';
    case VideoTapeRentalStores = '7841';
    case VocationalTradeSchools = '8249';
    case WatchJewelryRepair = '7631';
    case WeldingRepair = '7692';
    case WholesaleClubs = '5300';
    case WigAndToupeeStores = '5698';
    case WiresMoneyOrders = '4829';
    case WomensAccessoryAndSpecialtyShops = '5631';
    case WomensReadyToWearStores = '5621';
    case WreckingAndSalvageYards = '5935';

    public function getLabel(): string
    {
        return match ($this) {
            self::AcRefrigerationRepair => 'A/C Repair',
            self::AccountingBookkeepingServices => 'Accounting',
            self::AdvertisingServices => 'Advertising',
            self::AgriculturalCooperative => 'Agricultural Cooperative',
            self::AirlinesAirCarriers => 'Airlines, Air Carriers',
            self::AirportsflyingFields => 'Airports, Flying Fields',
            self::AmbulanceServices => 'Ambulance Services',
            self::AntiqueReproductions => 'Antique Reproductions',
            self::AntiqueShops => 'Antique Shops',
            self::Aquariums => 'Aquariums',
            self::ArchitecturalSurveyingServices => 'Architectural',
            self::ArtDealersAndGalleries, self::ArtistsSupplyAndCraftShops => 'Arts',
            self::AutomobileAssociations, self::AutoBodyRepairShops, self::AutoPaintShops, self::AutoServiceShops, self::AutoAndHomeSupplyStores, self::AutomotivePartsAndAccessoriesStores, self::AutomotiveTireStores => 'Auto',
            self::Bakeries => 'Bakeries',
            self::BandsOrchestras => 'Music',
            self::BarberAndBeautyShops => 'Beauty',
            self::BettingCasinoGambling => 'Betting/Casino',
            self::BicycleShops => 'Bicycle Shops',
            self::BilliardPoolEstablishments => 'Billiard/Pool',
            self::BoatDealers => 'Boat',
            self::BoatRentalsAndLeases => 'Boat Rentals and Leases',
            self::BookStores, self::BooksPeriodicalsAndNewspapers => 'Books',
            self::BowlingAlleys => 'Bowling Alleys',
            self::BusLines => 'Bus Lines',
            self::BusinessSecretarialSchools => 'Business Schools',
            self::BuyingShoppingServices => 'Buying/Shopping',
            self::CableSatelliteAndOtherPayTelevisionAndRadio => 'Cable/TV',
            self::CameraAndPhotographicSupplyStores => 'Photography',
            self::CandyNutAndConfectioneryStores => 'Candy',
            self::CarRentalAgencies => 'Car Rental',
            self::CarWashes => 'Car Wash',
            self::CarAndTruckDealersNewUsed, self::CarAndTruckDealersUsedOnly => 'Car Dealers',
            self::CarpentryServices => 'Carpentry',
            self::CarpetUpholsteryCleaning => 'Carpet Cleaning',
            self::Caterers => 'Caterers',
            self::CharitableAndSocialServiceOrganizationsFundraising => 'Charity',
            self::ChemicalsAndAlliedProducts => 'Chemicals',
            self::ChildCareServices => 'Child Care',
            self::ChildrensAndInfantsWearStores => 'Children Clothing',
            self::ChiropodistsPodiatrists => 'Podiatrists',
            self::Chiropractors => 'Chiropractors',
            self::CigarStoresAndStands => 'Tobacco',
            self::CivicSocialFraternalAssociations => 'Associations',
            self::CleaningAndMaintenance => 'Cleaning',
            self::ClothingRental => 'Clothing Rental',
            self::CollegesUniversities => 'Education',
            self::CommercialEquipment => 'Equipment',
            self::CommercialFootwear => 'Commercial Footwear',
            self::CommercialPhotographyArtAndGraphics => 'Photography',
            self::CommuterTransportAndFerries => 'Transport',
            self::ComputerNetworkServices => 'Computer Network',
            self::ComputerProgramming => 'Computer Programming',
            self::ComputerRepair => 'Computer Repair',
            self::ComputerSoftwareStores, self::ComputersPeripheralsAndSoftware => 'Computers',
            self::ConcreteWorkServices => 'Concrete Work',
            self::ConstructionMaterials => 'Construction',
            self::ConsultingPublicRelations => 'Consulting',
            self::CorrespondenceSchools => 'Correspondence Schools',
            self::CosmeticStores => 'Cosmetic Stores',
            self::CounselingServices => 'Counseling Services',
            self::CountryClubs => 'Country Clubs',
            self::CourierServices => 'Courier',
            self::CourtCosts => 'Legal',
            self::CreditReportingAgencies => 'Credit Reporting Agencies',
            self::CruiseLines => 'Cruise Lines',
            self::DairyProductsStores => 'Dairy Products Stores',
            self::DanceHallStudiosSchools => 'Dance',
            self::DentistsOrthodontists => 'Dental',
            self::DepartmentStores => 'Department Stores',
            self::DetectiveAgencies => 'Detective Agencies',
            self::DigitalGoodsMediaBooksMoviesMusic, self::DigitalGoodsApplications, self::DigitalGoodsGames, self::DigitalGoodsLargeVolume => 'Digital Goods',
            self::DirectMarketingCatalogMerchant, self::DirectMarketingCombinationCatalogAndRetailMerchant, self::DirectMarketingInboundTelemarketing, self::DirectMarketingInsuranceServices, self::DirectMarketingOther, self::DirectMarketingOutboundTelemarketing, self::DirectMarketingSubscription, self::DirectMarketingTravel => 'Marketing',
            self::DiscountStores => 'Discount Stores',
            self::Doctors => 'Doctors',
            self::DoorToDoorSales => 'Door-To-Door Sales',
            self::DraperyWindowCoveringAndUpholsteryStores => 'Home Decor',
            self::DrinkingPlaces => 'Drinking Places',
            self::DrugStoresAndPharmacies, self::DrugsDrugProprietariesAndDruggistSundries => 'Pharmacy',
            self::DryCleaners => 'Dry Cleaners',
            self::DurableGoods => 'Goods',
            self::DutyFreeStores => 'Duty Free Stores',
            self::EatingPlacesRestaurants => 'Restaurants',
            self::EducationalServices => 'Educational',
            self::ElectricRazorStores => 'Electric Razor Stores',
            self::ElectricVehicleCharging => 'Electric Vehicle Charging',
            self::ElectricalPartsAndEquipment => 'Electrical',
            self::ElectricalServices => 'Electrical',
            self::ElectronicsRepairShops => 'Electronics Repair Shops',
            self::ElectronicsStores => 'Electronics Stores',
            self::ElementarySecondarySchools => 'Schools',
            self::EmergencyServicesGcasVisaUseOnly => 'Emergency',
            self::EmploymentTempAgencies => 'Employment',
            self::EquipmentRental => 'Equipment Rental',
            self::ExterminatingServices => 'Exterminating',
            self::FamilyClothingStores => 'Family Clothing Stores',
            self::FastFoodRestaurants => 'Fast Food Restaurants',
            self::FinancialInstitutions => 'Financial Institutions',
            self::FinesGovernmentAdministrativeEntities => 'Fines - Government Administrative Entities',
            self::FireplaceFireplaceScreensAndAccessoriesStores => 'Fireplace, Fireplace Screens, and Accessories Stores',
            self::FloorCoveringStores => 'Floor Covering Stores',
            self::Florists => 'Florists',
            self::FloristsSuppliesNurseryStockAndFlowers => 'Florists',
            self::FreezerAndLockerMeatProvisions => 'Freezer and Locker Meat Provisioners',
            self::FuelDealersNonAutomotive => 'Fuel',
            self::FuneralServicesCrematories => 'Funeral',
            self::FurnitureRepairRefinishing, self::FurnitureHomeFurnishingsAndEquipmentStoresExceptAppliances => 'Furniture',
            self::FurriersAndFurShops => 'Fur',
            self::GeneralServices => 'General',
            self::GiftCardNoveltyAndSouvenirShops => 'Gifts',
            self::GlassPaintAndWallpaperStores, self::GlasswareCrystalStores => 'Glass/Paint',
            self::GolfCoursesPublic => 'Golf Courses - Public',
            self::GovernmentLicensedOnlineCasionsOnlineGamblingUsRegionOnly, self::GovernmentServices, self::GovernmentLicensedHorseDogRacingUsRegionOnly, self::GovernmentOwnedLotteriesNonUsRegion, self::GovernmentOwnedLotteriesUsRegionOnly => 'Government',
            self::GroceryStoresSupermarkets => 'Grocery',
            self::HardwareStores => 'Hardware Stores',
            self::HardwareEquipmentAndSupplies => 'Hardware',
            self::HealthAndBeautySpas => 'Spa',
            self::HearingAidsSalesAndSupplies => 'Hearing Aids',
            self::HeatingPlumbingAc => 'HVAC',
            self::HobbyToyAndGameShops => 'Toys/Games',
            self::HomeSupplyWarehouseStores => 'Home Supply',
            self::Hospitals => 'Hospitals',
            self::HotelsMotelsAndResorts => 'Hotels',
            self::HouseholdApplianceStores => 'Household Appliance Stores',
            self::IndustrialSupplies => 'Industrial',
            self::InformationRetrievalServices => 'Information Retrieval',
            self::InsuranceUnderwritingPremiums => 'Insurance',
            self::IntraCompanyPurchases => 'Intra-Company Purchases',
            self::JewelryStoresWatchesClocksAndSilverwareStores => 'Jewelry',
            self::LandscapingServices => 'Landscaping',
            self::Laundries => 'Laundries',
            self::LaundryCleaningServices => 'Laundry',
            self::LegalServicesAttorneys => 'Legal',
            self::LuggageAndLeatherGoodsStores => 'Luggage',
            self::LumberBuildingMaterialsStores => 'Lumber',
            self::MarinasServiceAndSupplies => 'Marina',
            self::MasonryStoneworkAndPlaster => 'Masonry',
            self::MassageParlors => 'Massage Parlors',
            self::MedicalServices => 'Medical Services',
            self::MedicalAndDentalLabs, self::MedicalDentalOphthalmicAndHospitalEquipmentAndSupplies => 'Medical',
            self::MembershipOrganizations => 'Membership Organizations',
            self::MensAndBoysClothingAndAccessoriesStores, self::MensWomensClothingStores => 'Clothing',
            self::MetalServiceCenters => 'Metal Service Centers',
            self::MiscellaneousApparelAndAccessoryShops,
            self::MiscellaneousAutoDealers,
            self::MiscellaneousBusinessServices,
            self::MiscellaneousFoodStores,
            self::MiscellaneousGeneralMerchandise,
            self::MiscellaneousGeneralServices,
            self::MiscellaneousHomeFurnishingSpecialtyStores,
            self::MiscellaneousPublishingAndPrinting,
            self::MiscellaneousRecreationServices,
            self::MiscellaneousRepairShops,
            self::MiscellaneousSpecialtyRetail => 'Miscellaneous',
            self::MobileHomeDealers => 'Mobile Home',
            self::MotionPictureTheaters => 'Motion Picture Theaters',
            self::MotorFreightCarriersAndTrucking => 'Motor Freight',
            self::MotorHomesDealers => 'Motor Homes',
            self::MotorVehicleSuppliesAndNewParts => 'Motor Vehicle Supplies and New Parts',
            self::MotorcycleShopsAndDealers, self::MotorcycleShopsDealers => 'Motorcycle Shops',
            self::MusicStoresMusicalInstrumentsPianosAndSheetMusic => 'Music',
            self::NewsDealersAndNewsstands => 'News',
            self::NondurableGoods => 'Nondurable Goods',
            self::NurseriesLawnAndGardenSupplyStores => 'Garden',
            self::NursingPersonalCare => 'Nursing/Personal Care',
            self::OfficeAndCommercialFurniture => 'Office Furniture',
            self::OpticiansEyeglasses, self::OptometristsOphthalmologist => 'Eye Care',
            self::OrthopedicGoodsProstheticDevices => 'Orthopedic',
            self::Osteopaths => 'Osteopaths',
            self::PackageStoresBeerWineAndLiquor => 'Liquor',
            self::PaintsVarnishesAndSupplies => 'Paint',
            self::ParkingLotsGarages => 'Parking',
            self::PassengerRailways => 'Railways',
            self::PawnShops => 'Pawn',
            self::PetShopsPetFoodAndSupplies => 'Pets',
            self::PetroleumAndPetroleumProducts => 'Petroleum',
            self::PhotoDeveloping => 'Photography',
            self::PhotographicStudios => 'Photographic Studios',
            self::PhotographicPhotocopyMicrofilmEquipmentAndSupplies => 'Photography',
            self::PictureVideoProduction => 'Video Production',
            self::PieceGoodsNotionsAndOtherDryGoods => 'Textiles',
            self::PlumbingHeatingEquipmentAndSupplies => 'Plumbing',
            self::PoliticalOrganizations => 'Political Organizations',
            self::PostalServicesGovernmentOnly => 'Postal',
            self::PreciousStoneAndMetalsWatchesAndJewelry => 'Jewelry',
            self::ProfessionalServices => 'Professional',
            self::PublicWarehousingAndStorage => 'Storage',
            self::QuickCopyReproAndBlueprint => 'Printing',
            self::Railroads => 'Railroads',
            self::RealEstateAgentsAndManagersRentals => 'Real Estate',
            self::RecordStores => 'Record Stores',
            self::RecreationalVehicleRentals => 'RV Rental',
            self::ReligiousGoodsStores => 'Religious Goods Stores',
            self::ReligiousOrganizations => 'Religious Organizations',
            self::RoofingSidingSheetMetal => 'Roofing',
            self::SecretarialSupportServices => 'Secretarial Support',
            self::SecurityBrokersDealers => 'Security Brokers/Dealers',
            self::ServiceStations => 'Service Stations',
            self::SewingNeedleworkFabricAndPieceGoodsStores => 'Sewing',
            self::ShoeRepairHatCleaning => 'Shoe Repair',
            self::ShoeStores => 'Shoe Stores',
            self::SmallApplianceRepair => 'Small Appliance Repair',
            self::SnowmobileDealers => 'Snowmobile',
            self::SpecialTradeServices => 'Special Trade',
            self::SpecialtyCleaning => 'Specialty Cleaning',
            self::SportingGoodsStores => 'Sporting Goods Stores',
            self::SportingRecreationCamps => 'Sports Camps',
            self::SportsClubsFields => 'Sports Clubs/Fields',
            self::SportsAndRidingApparelStores => 'Sports Apparel',
            self::StampAndCoinStores => 'Collectibles',
            self::StationeryStoresOfficeAndSchoolSupplyStores => 'Stationery Stores, Office, and School Supply Stores',
            self::StationeryOfficeSuppliesPrintingAndWritingPaper => 'Office Supplies',
            self::SwimmingPoolsSales => 'Swimming Pools',
            self::TuiTravelGermany => 'TUI Travel - Germany',
            self::TailorsAlterations => 'Tailoring',
            self::TaxPaymentsGovernmentAgencies => 'Tax Payments - Government Agencies',
            self::TaxPreparationServices => 'Tax Preparation',
            self::TaxicabsLimousines => 'Transportation',
            self::TelecommunicationEquipmentAndTelephoneSales => 'Telecom',
            self::TelecommunicationServices => 'Telecommunication Services',
            self::TelegraphServices => 'Telegraph',
            self::TentAndAwningShops => 'Outdoor Gear',
            self::TestingLaboratories => 'Testing Laboratories',
            self::TheatricalTicketAgencies => 'Tickets',
            self::Timeshares => 'Timeshares',
            self::TireRetreadingAndRepair => 'Tire Repair',
            self::TollsBridgeFees => 'Tolls',
            self::TouristAttractionsAndExhibits => 'Tourism',
            self::TowingServices => 'Towing',
            self::TrailerParksampgrounds => 'Camping',
            self::TransportationServices => 'Transportation Services',
            self::TravelAgenciesTourOperators => 'Travel',
            self::TruckUtilityTrailerRentals => 'Truck Rental',
            self::TypesettingPlateMakingAndRelatedServices => 'Printing',
            self::TypewriterStores => 'Typewriter Stores',
            self::UniformsCommercialClothing => 'Clothing',
            self::UsedMerchandiseAndSecondhandStores => 'Secondhand',
            self::Utilities => 'Utilities',
            self::VarietyStores => 'Variety Stores',
            self::VeterinaryServices => 'Veterinary',
            self::VideoAmusementGameSupplies, self::VideoGameArcades, self::VideoTapeRentalStores => 'Entertainment',
            self::VocationalTradeSchools => 'Vocational/Trade Schools',
            self::WatchJewelryRepair => 'Jewelry Repair',
            self::WeldingRepair => 'Welding Repair',
            self::WholesaleClubs => 'Wholesale Clubs',
            self::WigAndToupeeStores => 'Hair Products',
            self::WiresMoneyOrders => 'Money Transfer',
            self::WomensAccessoryAndSpecialtyShops, self::WomensReadyToWearStores => 'Women',
            self::WreckingAndSalvageYards => 'Salvage',
            default => 'Other',
        };
    }
}
